export  {LandingPage} from "./LandingPage";
export {Login} from "./Auth/Login";
export {SignUp} from "./Auth/SignUp";
export {VerificacionCorreo} from "./Auth/VerificacionCorreo";
export {Dashboard} from "./Home/Dashboard";
export {ProfileInfo} from "./Home/ProfileInfo";
export {EditResume} from "./ResumeUpdate/EditResume";
export {Analisis} from "./AnalisisCv";
export {ProcesarUrl} from "./ProcesarUrl";
